# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
