"""MARC preprocessors for data import into FOLIO."""

from ._preprocessors import (
    MARCPreprocessor,
    clean_999_fields,
    clean_empty_contributors,
    clean_empty_fields,
    clean_non_ff_999_fields,
    copy_240_to_245_if_no_245,
    fix_bib_leader,
    mark_deleted,
    move_856z_to_856y,
    move_authority_subfield_9_to_0_all_controllable_fields,
    normalize_subfield_codes,
    populate_blank_008_0_5,
    prepend_abes_prefix_001,
    prepend_ppn_prefix_001,
    prepend_prefix_001,
    remove_non_numeric_fields,
    remove_sudoc_prefixes,
    strip_999_ff_fields,
    sudoc_supercede_prep,
)

__all__ = [
    "MARCPreprocessor",
    "clean_999_fields",
    "clean_empty_contributors",
    "clean_empty_fields",
    "clean_non_ff_999_fields",
    "copy_240_to_245_if_no_245",
    "fix_bib_leader",
    "mark_deleted",
    "move_856z_to_856y",
    "move_authority_subfield_9_to_0_all_controllable_fields",
    "normalize_subfield_codes",
    "populate_blank_008_0_5",
    "prepend_abes_prefix_001",
    "prepend_ppn_prefix_001",
    "prepend_prefix_001",
    "remove_non_numeric_fields",
    "remove_sudoc_prefixes",
    "strip_999_ff_fields",
    "sudoc_supercede_prep",
]
